[general]
openai_api_key = "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"
google_maps_api_key = "AIzaSyBZ54CrwbNjBiKKs-4NydriYQTp0yEGFlM"
gemini_api_key = "AIzaSyA8CHnU_1P-UMjwR9bK9Fn77zmymPNXC5Y"

